# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config/units.tsv


ref:
  # Ensembl species name [homo_sapiens, or mus_musculus]
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 100
  # Genome build
  build: GRCh38

ref_index:
  bwa-index: "/cluster/projects/mcgahalab/ref/genomes/human/GRCh38/BWAIndex"
  genome: "/cluster/projects/mcgahalab/ref/genomes/human/GRCh38/genome.fasta"

trimming:
  activate: False

mergeReads:
  activate: False

pca:
  activate: True
  labels:
    # columns of sample sheet to use for PCA
    - condition

genotyping:
  target: "/cluster/projects/mcgahalab/ref/dbsnp/b151_GRCh38p7/bed/common_all_20180418.bed"
  min_n: 2

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    treated-vs-untreated:
      - treated
      - untreated
  model: ~condition

params:
  cutadapt-pe: ""
  cutadapt-se: ""

gsea:
  min_base_mean: 50
  max_p: 0.05

star:
  star-genome: "/cluster/projects/mcgahalab/ref/genomes/human/GRCh38/STARindex/sjdb_74"
  gtf: "/cluster/projects/mcgahalab/ref/genomes/human/GRCh38/GTF/genome.gtf"
  params: ""
